=== johnhelmuth/cluster-map/data/schemas/characters/character.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://in-dire-straits.space/data/schemas/characters/character.schema.json",
  "title": "Character",
  "description": "A character in a Role Playing Game.",
  "type": "object",
  "properties": {
    "type": {
      "description": "The type of thingy the data describes, 'character'.",
      "type": "string",
      "const": "character"
    },
    "schemaVersion": {
      "description": "The version of the schema for the data.",
      "type": "string",
      "const": "1"
    },
    "id": {
      "title": "ID",
      "description": "Unique identifier for the character.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "The name of the character.",
      "type": "string"
    },
    "playerName": {
      "description": "The name of the player of the character.",
      "type": "string"
    },
    "campaigns": {
      "title": "Campaigns",
      "description": "A list of campaigns this character is in.",
      "type": "array",
      "items": {
        "type": "string",
        "title": "Campaign name",
        "description": "The name of one of the campaigns the character is in."
      }
    },
    "description": {
      "description": "The description of the character.",
      "type": "string"
    },
    "characterType": {
      "title": "Character type",
      "description": "The type of character, PC, NPC, Mob, Ship, etc.",
      "type": "string",
      "enum": [
        "PC",
        "NPC",
        "ship",
        "mob"
      ]
    },
    "refresh": {
      "description": "The current minimum number of Fate points the player of this character starts with at the beginning of a session.",
      "type": "integer",
      "minimum": 1,
      "default": 3
    },
    "fatePoints": {
      "description": "The current number of Fate points the player of this character currently has.",
      "type": "integer",
      "minimum": 0,
      "default": 3
    },
    "aspects": {
      "description": "The Aspects describing the character.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "aspectType": {
            "description": "The type of Aspect",
            "type": "string",
            "enum": [
              "High Concept",
              "Trouble",
              "Relationship",
              "Reason to Race",
              "Oneshot Reason",
              "Other"
            ]
          },
          "name": {
            "description": "The name of the Aspect",
            "type": "string"
          },
          "description": {
            "description": "A description of the Aspect, giving a little more context.",
            "type": "string"
          },
          "freeInvokes": {
            "type": "number",
            "description": "How many Free Invokes are currently on the Aspect",
            "minimum": 0,
            "default": 0
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "images": {
      "description": "A list of images representing the character, to be included on the character's sheet.",
      "title": "Character Images",
      "type": "array",
      "items": {
        "description": "The details about an image.",
        "title": "Image",
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "The URI of an image.",
            "title": "Image URI"
          },
          "caption": {
            "description": "The caption to be displayed with the image.",
            "title": "Image Caption",
            "type": "string"
          }
        },
        "required": ["uri"]
      },
      "minItems": 1
    },
    "traitType": {
      "type": "string",
      "description": "The type of the properties of the character used as a bonus on a dice roll to resolve actions.",
      "enum": [
        "skill",
        "approach",
        "profession",
        "other"
      ]
    },
    "traits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the trait, like 'Notice', 'Careful', or 'Warrior'"
          },
          "rank": {
            "type": "integer",
            "description": "The bonus applied to a resolution roll when this trait is applicable.",
            "minimum": 0
          }
        },
        "required": [
          "name",
          "rank"
        ]
      }
    },
    "stunts": {
      "type": "array",
      "description": "A list of the stunts the character can use.",
      "items": {
        "type": "object",
        "description": "A stunt the character can use.",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the stunt"
          },
          "description": {
            "type": "string",
            "description": "A description of the stunt describe the mechanical or narrative effect of the stunt and the conditions under which it applies."
          },
          "parameters": {
            "type": "object",
            "description": "The details of the mechanical effect of a stunt.",
            "properties": {
              "trait": {
                "type": "string",
                "description": "The trait (from the 'trait[].name' list) that the mechanics of this stunt applies."
              },
              "modifier": {
                "type": "integer",
                "description": "How many points should be applied as the mechanical effect of the stunt. It can either add to a roll or the shifts of effect from the roll when successful.",
                "minimum": 1
              },
              "actions": {
                "type": "array",
                "description": "The action types to which the mechanical effect applies.",
                "items": {
                  "enum": [
                    "Overcome",
                    "CaA",
                    "Defend",
                    "Attack"
                  ]
                },
                "uniqueItems": true,
                "minItems": 1
              },
              "modificationType": {
                "type": "string",
                "description": "The part of the resolution task to which the modifier is applied, either the total of the roll, or the total of the effect when the roll is successful.",
                "enum": [
                  "roll",
                  "effect"
                ],
                "default": "roll"
              }
            }
          }
        },
        "required": [
          "description"
        ]
      }
    },
    "tracks": {
      "type": "array",
      "description": "The data structures used to track the current state of the character.",
      "items": {
        "type": "object",
        "properties": {
          "trackId": {
            "type": "string",
            "description": "A unique identifier for this track on the character to which it is tied."
          },
          "trackLabel": {
            "type": "string",
            "description": "The label or title for this track."
          },
          "showSoakAmount": {
            "type": "boolean",
            "description": "Should the amount of soak the boxes in this track be displayed to the user?"
          },
          "boxes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "isUsed": {
                  "type": "boolean",
                  "description": "Has the box been used to soak shifts of effect?"
                },
                "soakValue": {
                  "type": "number",
                  "description": "How many shifts of effect the box can soak."
                }
              },
              "required": [
                "isUsed",
                "soakValue"
              ]
            }
          },
          "aspect": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "The Aspect representing the consequence in this track."
              },
              "freeInvokes": {
                "type": "number",
                "description": "How many Free Invokes the consequence already has."
              },
              "state": {
                "type": "string",
                "enum": [
                  "free",
                  "used",
                  "recovering"
                ]
              }
            },
            "required": [
              "name",
              "freeInvokes",
              "state"
            ]
          }
        },
        "required": [
          "trackId"
        ]
      }
    },
    "notes": {
      "title": "Notes",
      "description": "Section for notes about the character",
      "type": "array",
      "items": {
        "description": "A line of a multi-text notes field. Supports Markdown",
        "type": "string"
      }
    },
    "tags": {
      "title": "Tags",
      "description": "Arbitrary tags to be applied to the character.",
      "type": "array",
      "items": {
        "title": "Tag",
        "description": "A tag that applies to a character.",
        "type": "string",
        "minLength": 2
      }
    }
  },
  "required": [
    "type",
    "schemaVersion",
    "id",
    "name"
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/ikari-kintsugi.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "ikari-kintsugi",
  "name": "Ikari Kintsugi",
  "playerName": "Bea",
  "description": "Young woman in dark attire with gold colored scarring.",
  "campaigns": [
    "one-shot-3"
  ],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Well Connected Pickpocket"
    },
    {
      "aspectType": "Trouble",
      "name": "Abrasive to Authority"
    },
    {
      "aspectType": "Oneshot Reason",
      "name": "Low class serving girl on the Lam",
      "description": "Kintsugi stole some jewelry from Lady Ariana Zanetti, and was lying low in an inn on the road between Alodon and Abilene.\n\nShe was working as a serving girl there when the murder of Lady Charrisse Grant took place."
    },
    {
      "aspectType": "Relationship",
      "name": "Murrieta Owes Me Money"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Burglary",
      "rank": 4
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "notes": [
    "Known alias: Elise."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/jim-dade.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "jim-dade",
  "name": "Jim Dade",
  "playerName": "Robert L",
  "campaigns": ["campaign-1"],
  "characterType": "PC",
  "description": "Currently morphed to appear as a military grown vat clone. Vat clones look all the same. They look kind of like Lee Majors in his prime.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Charismatic cyborg military infiltration scout"
    },
    {
      "aspectType": "Trouble",
      "name": "Hiding from assassins with unknown motivations"
    },
    {
      "name": "Modified Cyber-Heart that requires constant sugar intake"
    },
    {
      "name": "Uses their cover to hide the cold calculations"
    },
    {
      "name": "Dangerous AI-predictive combat reflex responses"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Rapport",
      "rank": 4
    },
    {
      "name": "Deceive",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    },
    {
      "name": "Burglary",
      "rank": 2
    },
    {
      "name": "Fight",
      "rank": 2
    },
    {
      "name": "Shoot",
      "rank": 2
    },
    {
      "name": "Athletics",
      "rank": 1
    },
    {
      "name": "Drive",
      "rank": 1
    },
    {
      "name": "Investigate",
      "rank": 1
    },
    {
      "name": "Stealth",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "stunts": [
    {
      "name": "Feint",
      "description": "When it looks like you're going to go right, you go left. And vice versa. +2 to create advantages with Deceive that relate to confusion and misdirection in physical combat. (adapted from http://dfrpg-resources.wikispaces.com/Stunts)",
      "parameters": {
        "trait": "Deceive",
        "modifier": 2,
        "actions": ["CaA"],
        "modificationType": "roll"
      }
    },
    {
      "name": "Hatpin Maestro",
      "description": "You don’t ever have to spend a fate point to declare that you have the proper tools for lockpicking or disabling a device, even in extreme situations (like being imprisoned and separated from all your stuff). This source of opposition is just off the table. (adapted from Spirit of the Century SRD, §6.6.2)"
    },
    {
      "name": "Houdini",
      "description": "You could be found by the police standing next to a burned-down church with a handful of matches and a can of gasoline and still get away scot-free. +2 to Deceive when using it to defend against attempts to discern or prove your involvement in a crime. (adapted from http://dfrpg-resources.wikispaces.com/Stunts)",
      "parameters": {
        "trait": "Deceive",
        "modifier": 2,
        "actions": ["Defend"],
        "modificationType": "roll"
      }
    }
  ],
  "notes": [
    "#### Biography",
    "",
    "\"Jim\" got mortally wounded and left for dead on a routine scouting mission one day. His company retrieved him. They rebuilt him. They made him better.",
    "It wasn’t a routine mission after all. They could not let the information he gathered die with him. What information? Jim doesn’t know. They had to replace part of his brain. How much? The new \"Jim\" doesn’t really care. All he knows is that his tour has been extended for everyone involved to recoup the costs of saving his life with cybernetic implants.",
    "Now someone has been going around killing off or abducting all the scout infiltrator cyborgs like himself. Who could it be?",
    "",
    "* A division of the military trying to cover up that dangerously buggy combat reflexes they programmed into him?",
    "* Another human government agency?",
    "* A near-humanoid alien agency?",
    "* A rival cybernetics corporation?",
    "* Maybe it’s \"The General\"?",
    "",
    "\"The General\" swooped in, provided Jim with a cover identity (Jim Dade) and a classified codename to get resources. Then \"The General\" ordered him to lie low while they figured all of this out. As a matter of fact, go join this specific ship crew. \"The General\" promises to call and send Jim on missions to investigate who is out to kill off his cybernetics model.",
    "Oh, and \"The General\" still has missions for Jim to complete with orders to, \"try not to expose your real identity or capabilities, okay?\". The only other mission Jim has been sent on (other than joining the current crew) was a pet retrieval mission for \"The General\". Jim kind of suspects he was sent in as a disposable asset on that one.",
    "",
    "#### Inventory",
    "",
    "* Raygun secured in belt holster",
    "* Belt with an over-sized belt-buckle holding up today’s idea of throw-back fashions",
    "* Chest hair",
    "* A cigarette-like case, sized to carry toothpicks",
    "* Comms device, wipes all personal data / app logins over 18 Earth hours old, only retaining ID documents, bank routing and account information",
    "* A bag full of sugary treats",
    "* Winning smile"
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/jithal.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "jithal",
  "name": "Jithal",
  "playerName": "Kit",
  "description": "4 armed, eyeless, lamia who sees through radar",
  "campaigns": ["campaign-1"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Last Grulvaxian Expert Engineer"
    },
    {
      "aspectType": "Trouble",
      "name": "Stranger in a Strange Land"
    },
    {
      "name": "Jithal can fix that"
    },
    {
      "name": "Soft spot for scientists"
    },
    {
      "name": "Charmingly Curious"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Engineering",
      "rank": 4
    },
    {
      "name": "Will",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    },
    {
      "name": "Academics",
      "rank": 2
    },
    {
      "name": "Provoke",
      "rank": 2
    },
    {
      "name": "Athletics",
      "rank": 2
    },
    {
      "name": "Pilot",
      "rank": 1
    },
    {
      "name": "Stealth",
      "rank": 1
    },
    {
      "name": "Rapport",
      "rank": 1
    },
    {
      "name": "Investigate",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/Ships/ned-tugboat.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "ned-tugboat",
  "name": "NED Tugboat",
  "characterType": "ship",
  "campaigns": ["campaign-2"],
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Small but powerful"
    },
    {
      "name": "Yes, She's Ugly"
    }
  ],
  "traitType": "other",
  "traits": [
    {
      "name": "Defense",
      "rank": 0
    },
    {
      "name": "Movement",
      "rank": 0
    },
    {
      "name": "Sensors",
      "rank": 0
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "notes": [
    "* Bunks for a crew of 6.  \n* Can be safely crewed by 3  \n* In-system drive  \n* FTL Slipstream drive  \n* Power reactor  \n* Sensor suite  \n* Computer System  \n* Fuel storage for 3 consecutive Slipstream jumps  \n* Life support (air/food) for 6 humans for 1 year  \n* Atmosphere capable (can land and take off from planets)  \n* Small cargo bay  \n* 1 large cargo hatch into cargo bay (no airlock)  \n* 1 personnel sized airlock  \n* Size: 25 meters x 10 meters x 10 meters. In-system engines take up about half of that volume."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/scout-4e0061377.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "scout-4e0061377",
  "name": "Scout 4e0061377",
  "playerName": "Pete",
  "description": "",
  "campaigns": ["campaign-2"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 4,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "War Veteran Recon Clone that Lives to Recon"
    },
    {
      "aspectType": "Trouble",
      "name": "I Haven't Found Satisfaction in Other Tasks"
    },
    {
      "name": "I Don't Like Having to Learn New Things"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Stealth",
      "rank": 4
    },
    {
      "name": "Physique",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/delilah-land.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "delilah",
  "name": "Delilah \"Deli\" Land",
  "playerName": "Bea",
  "description": "",
  "campaigns": ["campaign-2"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Transhuman Transgender Engineer"
    },
    {
      "aspectType": "Trouble",
      "name": ""
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Engineering",
      "rank": 4
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/sample-character.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "0",
  "name": "Joe Sample",
  "description": "Joe is a simple guy, trying to be a good man in a hard world.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Protagonist for Pay",
      "description": "Joe is an ex-cop who now works as a Private Investigator and is definitely the hero of his own story."
    },
    {
      "aspectType": "Trouble",
      "name": "Too good for this world",
      "description": "Joe will do the right thing even though it turns out very badly for him."
    },
    {
      "aspectType": "Relationship",
      "name": "Must reconnect with my estranged daughter Emily",
      "description": "Joe's adult daughter Emily lives in the City but does not want contact with her father. She was raised by her mother after she divorced Joe because of his extreme work ethic and for fear of losing him to the dangers of his job."
    },
    {
      "name": "Custom tuned 1969 Mustang Mach 1"
    },
    {
      "name": "Carla's the best partner a man can have."
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Notice",
      "rank": 4
    },
    {
      "name": "Shoot",
      "rank": 3
    },
    {
      "name": "Empathy",
      "rank": 3
    },
    {
      "name": "Will",
      "rank": 2
    },
    {
      "name": "Athletics",
      "rank": 2
    },
    {
      "name": "Investigate",
      "rank": 2
    },
    {
      "name": "Fight",
      "rank": 1
    },
    {
      "name": "Physique",
      "rank": 1
    },
    {
      "name": "Drive",
      "rank": 1
    },
    {
      "name": "Resources",
      "rank": 1
    }
  ],
  "stunts": [
    {
      "name": "Resolute",
      "description": "In order to steel myself to action, I get +2 to a Will roll to Create an Advantage representing my decision to follow through on that action. The Aspect created can be used to resist efforts to stop me completing the action.",
      "parameters": {
        "trait": "Will",
        "modifier": 2,
        "actions": ["CaA"]
      }
    }
  ]
}
