=== johnhelmuth/cluster-map/data/schemas/characters/character.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://in-dire-straits.space/data/schemas/characters/character.schema.json",
  "title": "Character",
  "description": "A character in a Role Playing Game.",
  "type": "object",
  "properties": {
    "type": {
      "description": "The type of thingy the data describes, 'character'.",
      "type": "string",
      "const": "character"
    },
    "schemaVersion": {
      "description": "The version of the schema for the data.",
      "type": "string",
      "const": "1"
    },
    "id": {
      "title": "ID",
      "description": "Unique identifier for the character.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "The name of the character.",
      "type": "string"
    },
    "playerName": {
      "description": "The name of the player of the character.",
      "type": "string"
    },
    "campaigns": {
      "title": "Campaigns",
      "description": "A list of campaigns this character is in.",
      "type": "array",
      "items": {
        "type": "string",
        "title": "Campaign name",
        "description": "The name of one of the campaigns the character is in."
      }
    },
    "description": {
      "description": "The description of the character.",
      "type": "string"
    },
    "characterType": {
      "title": "Character type",
      "description": "The type of character, PC, NPC, Mob, Ship, etc.",
      "type": "string",
      "enum": [
        "PC",
        "NPC",
        "ship",
        "mob"
      ]
    },
    "refresh": {
      "description": "The current minimum number of Fate points the player of this character starts with at the beginning of a session.",
      "type": "integer",
      "minimum": 1,
      "default": 3
    },
    "fatePoints": {
      "description": "The current number of Fate points the player of this character currently has.",
      "type": "integer",
      "minimum": 0,
      "default": 3
    },
    "aspects": {
      "description": "The Aspects describing the character.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "aspectType": {
            "description": "The type of Aspect",
            "type": "string",
            "enum": [
              "High Concept",
              "Trouble",
              "Relationship",
              "Reason to Race",
              "Oneshot Reason",
              "Other"
            ]
          },
          "name": {
            "description": "The name of the Aspect",
            "type": "string"
          },
          "description": {
            "description": "A description of the Aspect, giving a little more context.",
            "type": "string"
          },
          "freeInvokes": {
            "type": "number",
            "description": "How many Free Invokes are currently on the Aspect",
            "minimum": 0,
            "default": 0
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "images": {
      "description": "A list of images representing the character, to be included on the character's sheet.",
      "title": "Character Images",
      "type": "array",
      "items": {
        "description": "The details about an image.",
        "title": "Image",
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "The URI of an image.",
            "title": "Image URI"
          },
          "caption": {
            "description": "The caption to be displayed with the image.",
            "title": "Image Caption",
            "type": "string"
          }
        },
        "required": ["uri"]
      },
      "minItems": 1
    },
    "traitType": {
      "type": "string",
      "description": "The type of the properties of the character used as a bonus on a dice roll to resolve actions.",
      "enum": [
        "skill",
        "approach",
        "profession",
        "other"
      ]
    },
    "traits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the trait, like 'Notice', 'Careful', or 'Warrior'"
          },
          "rank": {
            "type": "integer",
            "description": "The bonus applied to a resolution roll when this trait is applicable.",
            "minimum": 0
          }
        },
        "required": [
          "name",
          "rank"
        ]
      }
    },
    "stunts": {
      "type": "array",
      "description": "A list of the stunts the character can use.",
      "items": {
        "type": "object",
        "description": "A stunt the character can use.",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the stunt"
          },
          "description": {
            "type": "string",
            "description": "A description of the stunt describe the mechanical or narrative effect of the stunt and the conditions under which it applies."
          },
          "parameters": {
            "type": "object",
            "description": "The details of the mechanical effect of a stunt.",
            "properties": {
              "trait": {
                "type": "string",
                "description": "The trait (from the 'trait[].name' list) that the mechanics of this stunt applies."
              },
              "modifier": {
                "type": "integer",
                "description": "How many points should be applied as the mechanical effect of the stunt. It can either add to a roll or the shifts of effect from the roll when successful.",
                "minimum": 1
              },
              "actions": {
                "type": "array",
                "description": "The action types to which the mechanical effect applies.",
                "items": {
                  "enum": [
                    "Overcome",
                    "CaA",
                    "Defend",
                    "Attack"
                  ]
                },
                "uniqueItems": true,
                "minItems": 1
              },
              "modificationType": {
                "type": "string",
                "description": "The part of the resolution task to which the modifier is applied, either the total of the roll, or the total of the effect when the roll is successful.",
                "enum": [
                  "roll",
                  "effect"
                ],
                "default": "roll"
              }
            }
          }
        },
        "required": [
          "description"
        ]
      }
    },
    "tracks": {
      "type": "array",
      "description": "The data structures used to track the current state of the character.",
      "items": {
        "type": "object",
        "properties": {
          "trackId": {
            "type": "string",
            "description": "A unique identifier for this track on the character to which it is tied."
          },
          "trackLabel": {
            "type": "string",
            "description": "The label or title for this track."
          },
          "showSoakAmount": {
            "type": "boolean",
            "description": "Should the amount of soak the boxes in this track be displayed to the user?"
          },
          "boxes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "isUsed": {
                  "type": "boolean",
                  "description": "Has the box been used to soak shifts of effect?"
                },
                "soakValue": {
                  "type": "number",
                  "description": "How many shifts of effect the box can soak."
                }
              },
              "required": [
                "isUsed",
                "soakValue"
              ]
            }
          },
          "aspect": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "The Aspect representing the consequence in this track."
              },
              "freeInvokes": {
                "type": "number",
                "description": "How many Free Invokes the consequence already has."
              },
              "state": {
                "type": "string",
                "enum": [
                  "free",
                  "used",
                  "recovering"
                ]
              }
            },
            "required": [
              "name",
              "freeInvokes",
              "state"
            ]
          }
        },
        "required": [
          "trackId"
        ]
      }
    },
    "notes": {
      "title": "Notes",
      "description": "Section for notes about the character",
      "type": "array",
      "items": {
        "description": "A line of a multi-text notes field. Supports Markdown",
        "type": "string"
      }
    },
    "tags": {
      "title": "Tags",
      "description": "Arbitrary tags to be applied to the character.",
      "type": "array",
      "items": {
        "title": "Tag",
        "description": "A tag that applies to a character.",
        "type": "string",
        "minLength": 2
      }
    }
  },
  "required": [
    "type",
    "schemaVersion",
    "id",
    "name"
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/steven-irwin.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "steven-irwin",
  "name": "Dr. Steven Irwin",
  "playerName": "Jon T.",
  "characterType": "PC",
  "campaigns": ["campaign-1"],
  "description": "A middle-aged field biologist eager to document the \"infinite diversity in infinite combinations\" of life in the galaxy.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Old-Fashioned Explorer-Naturalist"
    },
    {
      "aspectType": "Trouble",
      "name": "Dr. Crimini Has It Out For Me"
    },
    {
      "name": "My Good Friend Jithal"
    },
    {
      "name": "There's No Glory in Killing"
    },
    {
      "name": "Professor Ravenwood was Right"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Academics",
      "rank": 4
    },
    {
      "name": "Physique",
      "rank": 3
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Contacts",
      "rank": 2
    },
    {
      "name": "Shoot",
      "rank": 2
    },
    {
      "name": "Stealth",
      "rank": 2
    },
    {
      "name": "Will",
      "rank": 2
    },
    {
      "name": "Fight",
      "rank": 1
    },
    {
      "name": "Investigate",
      "rank": 1
    },
    {
      "name": "Notice",
      "rank": 1
    },
    {
      "name": "Pilot",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "stunts": [
    {
      "name": "Animal Handler",
      "description": "+2 to Overcome with Rapport when calming animals",
      "parameters": {
        "trait": "Rapport",
        "modifier": 2,
        "actions": ["Overcome"],
        "modificationType": "roll"
      }
    },
    {
      "name": "Toxin Exposure",
      "description": "+2 to Overcome with Physique when resisting poison",
      "parameters": {
        "trait": "Physique",
        "modifier": 2,
        "actions": ["Overcome"],
        "modificationType": "roll"
      }
    },
    {
      "name": "Indomitable",
      "description": "+2 to Defend with Will against fear or intimidation",
      "parameters": {
        "trait": "Will",
        "modifier": 2,
        "actions": ["Defend"],
        "modificationType": "roll"
      }
    }
  ],
  "notes": [
    "Equipment:",
    "- Field Clothing / Professional Clothing",
    "- Biocorder, Tablets, Scientific Kit, Utility Knife",
    "",
    "Weapons:",
    "- Pistol, Large Field Knife",
    "- Machete, Tranquilizer Rifle"
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/otarin.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "otarin",
  "name": "Otarin",
  "playerName": "Kit",
  "characterType": "PC",
  "campaigns": ["one-shot-2"],
  "description": "",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Sticky Fingered Career Thief"
    },
    {
      "aspectType": "Trouble",
      "name": "Fragile Ego"
    },
    {
      "name": "To prove I'm the best"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Burglary",
      "rank": 4
    },
    {
      "name": "Stealth",
      "rank": 3
    },
    {
      "name": "Athletics",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        },
        {
          "isUsed": false,
          "soakValue": 3
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/kiowynne.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "kiowynne",
  "name": "Kiowynne",
  "playerName": "Anne",
  "description": "Tall for a human woman, long black braided hair, deep tan, lots of gold jewelry.\n\nRed long coat, black, brown & gold vest, black cargo pants, combat boots.\n\nWeapon hidden under coat.",
  "campaigns": ["campaign-2"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Unflappable Badass"
    },
    {
      "aspectType": "Trouble",
      "name": "Can't say no to a pretty face"
    },
    {
      "name": "Collects strays"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Shoot",
      "rank": 4
    },
    {
      "name": "Fight",
      "rank": 3
    },
    {
      "name": "Provoke",
      "rank": 3
    },
    {
      "name": "Empathy",
      "rank": 2
    },
    {
      "name": "Contacts",
      "rank": 2
    },
    {
      "name": "Notice",
      "rank": 2
    }
  ],
  "stunts": [
    {
      "name": "Always looking for Danger",
      "description": "Because I've been in many situations where hidden weapons have put my life in danger, I have learned to spot them, and I get +2 on Notice Overcome rolls to identify when a character has hidden a weapon on themself.",
      "parameters": {
        "trait": "",
        "modifier": 2,
        "actions": ["Overcome"],
        "modificationType": "roll"
      }
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/NPCs/sample-character.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "0",
  "name": "Joe Sample",
  "characterType": "NPC",
  "description": "Joe is a simple guy, trying to be a good man in a hard world.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Protagonist for Pay",
      "description": "Joe is an ex-cop who now works as a Private Investigator and is definitely the hero of his own story.",
      "freeInvokes": 3
    },
    {
      "aspectType": "Trouble",
      "name": "Too good for this world",
      "description": "Joe will do the right thing even though it turns out very badly for him.",
      "freeInvokes": 0
    },
    {
      "aspectType": "Relationship",
      "name": "Must reconnect with my estranged daughter Emily",
      "description": "Joe's adult daughter Emily lives in the City but does not want contact with her father. She was raised by her mother after she divorced Joe because of his extreme work ethic and for fear of losing him to the dangers of his job.",
      "freeInvokes": 3
    },
    {
      "name": "Custom tuned 1969 Mustang Mach 1",
      "freeInvokes": 0
    },
    {
      "name": "Carla's the best partner a man can have.",
      "freeInvokes": 0
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Notice",
      "rank": 5
    },
    {
      "name": "Shoot",
      "rank": 4
    },
    {
      "name": "Empathy",
      "rank": 4
    },
    {
      "name": "Will",
      "rank": 3
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Investigate",
      "rank": 3
    },
    {
      "name": "Fight",
      "rank": 2
    },
    {
      "name": "Physique",
      "rank": 2
    },
    {
      "name": "Drive",
      "rank": 2
    },
    {
      "name": "Resources",
      "rank": 2
    },
    {
      "name": "Burglary",
      "rank": 1
    },
    {
      "name": "Contacts",
      "rank": 1
    },
    {
      "name": "Deceive",
      "rank": 1
    },
    {
      "name": "Provoke",
      "rank": 1
    },
    {
      "name": "Stealth",
      "rank": 1
    }
  ],
  "stunts": [
    {
      "name": "Resolute",
      "description": "In order to steel myself to action, I get +2 to a Will roll to Create an Advantage representing my decision to follow through on that action. The Aspect created can be used to resist efforts to stop me completing the action.",
      "parameters": {
        "trait": "Will",
        "modifier": 2,
        "actions": [
          "CaA"
        ]
      }
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": true,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        },
        {
          "isUsed": false,
          "soakValue": 3
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": true,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "Bruised knuckles",
        "freeInvokes": 2,
        "state": "used"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": true,
          "soakValue": 6
        }
      ],
      "aspect": {
        "name": "Compound fracture, left shin.",
        "freeInvokes": 1,
        "state": "recovering"
      }
    }
  ],
  "tags": ["detective"]
}

=== johnhelmuth/cluster-map/data/characters/NPCs/guts-matronas.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "guts-matronas",
  "name": "Sargent Guts Matronas",
  "characterType": "NPC",
  "campaigns": ["campaign-1", "one-shot-3"],
  "tags": ["home-system:golden-seed"],
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Long Suffering Bodyguard of Lady Ariana Zanetti"
    },
    {
      "name": "Too old for this shit, but it is my duty"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Fight",
      "rank": 3
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Physique",
      "rank": 2
    },
    {
      "name": "Shoot",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "notes": [
    "Carries a short sword and a revolver."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/bogart-wiley.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "bogart-wiley",
  "name": "Bogart \"Cousin Big Boy\" Wiley",
  "playerName": "Jon T",
  "characterType": "PC",
  "campaigns": ["one-shot-2"],
  "description": "The face with a lot of contacts.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "The Ultimate Cousin"
    },
    {
      "aspectType": "Trouble",
      "name": "I've made many more promises than I owed to me"
    },
    {
      "name": "I'm stealing this because I want my connections to stay relevant"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Contacts",
      "rank": 4
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Empathy",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        },
        {
          "isUsed": false,
          "soakValue": 3
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/crush-wilson.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "crush-wilson",
  "name": "\"Crush\" Wilson",
  "playerName": "Jon T.",
  "characterType": "PC",
  "description": "He's a Bearble with a taste for thrills and fixing things.",
  "campaigns": ["one-shot-1"],
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Surfer-Dude Bearble Engineer"
    },
    {
      "aspectType": "Trouble",
      "name": "The Girls in Every Port Have Unionized"
    },
    {
      "aspectType": "Reason to Race",
      "name": "I must ride the biggest wave"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Engineering",
      "rank": 5
    },
    {
      "name": "Pilot",
      "rank": 4
    },
    {
      "name": "Empathy",
      "rank": 4
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Stealth",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/templates/PC.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "XXXX",
  "name": "",
  "playerName": "",
  "description": "",
  "campaigns": [],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": ""
    },
    {
      "aspectType": "Trouble",
      "name": ""
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "",
      "rank": 4
    },
    {
      "name": "",
      "rank": 3
    },
    {
      "name": "",
      "rank": 3
    }
  ],
  "stunts": [
    {
      "name": "",
      "description": "",
      "parameters": {
        "trait": "",
        "modifier": 2,
        "actions": ["Overcome"],
        "modificationType": "roll"
      }
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}
