=== johnhelmuth/cluster-map/data/schemas/characters/character.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://in-dire-straits.space/data/schemas/characters/character.schema.json",
  "title": "Character",
  "description": "A character in a Role Playing Game.",
  "type": "object",
  "properties": {
    "type": {
      "description": "The type of thingy the data describes, 'character'.",
      "type": "string",
      "const": "character"
    },
    "schemaVersion": {
      "description": "The version of the schema for the data.",
      "type": "string",
      "const": "1"
    },
    "id": {
      "title": "ID",
      "description": "Unique identifier for the character.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "The name of the character.",
      "type": "string"
    },
    "playerName": {
      "description": "The name of the player of the character.",
      "type": "string"
    },
    "campaigns": {
      "title": "Campaigns",
      "description": "A list of campaigns this character is in.",
      "type": "array",
      "items": {
        "type": "string",
        "title": "Campaign name",
        "description": "The name of one of the campaigns the character is in."
      }
    },
    "description": {
      "description": "The description of the character.",
      "type": "string"
    },
    "characterType": {
      "title": "Character type",
      "description": "The type of character, PC, NPC, Mob, Ship, etc.",
      "type": "string",
      "enum": [
        "PC",
        "NPC",
        "ship",
        "mob"
      ]
    },
    "refresh": {
      "description": "The current minimum number of Fate points the player of this character starts with at the beginning of a session.",
      "type": "integer",
      "minimum": 1,
      "default": 3
    },
    "fatePoints": {
      "description": "The current number of Fate points the player of this character currently has.",
      "type": "integer",
      "minimum": 0,
      "default": 3
    },
    "aspects": {
      "description": "The Aspects describing the character.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "aspectType": {
            "description": "The type of Aspect",
            "type": "string",
            "enum": [
              "High Concept",
              "Trouble",
              "Relationship",
              "Reason to Race",
              "Oneshot Reason",
              "Other"
            ]
          },
          "name": {
            "description": "The name of the Aspect",
            "type": "string"
          },
          "description": {
            "description": "A description of the Aspect, giving a little more context.",
            "type": "string"
          },
          "freeInvokes": {
            "type": "number",
            "description": "How many Free Invokes are currently on the Aspect",
            "minimum": 0,
            "default": 0
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "images": {
      "description": "A list of images representing the character, to be included on the character's sheet.",
      "title": "Character Images",
      "type": "array",
      "items": {
        "description": "The details about an image.",
        "title": "Image",
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "The URI of an image.",
            "title": "Image URI"
          },
          "caption": {
            "description": "The caption to be displayed with the image.",
            "title": "Image Caption",
            "type": "string"
          }
        },
        "required": ["uri"]
      },
      "minItems": 1
    },
    "traitType": {
      "type": "string",
      "description": "The type of the properties of the character used as a bonus on a dice roll to resolve actions.",
      "enum": [
        "skill",
        "approach",
        "profession",
        "other"
      ]
    },
    "traits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the trait, like 'Notice', 'Careful', or 'Warrior'"
          },
          "rank": {
            "type": "integer",
            "description": "The bonus applied to a resolution roll when this trait is applicable.",
            "minimum": 0
          }
        },
        "required": [
          "name",
          "rank"
        ]
      }
    },
    "stunts": {
      "type": "array",
      "description": "A list of the stunts the character can use.",
      "items": {
        "type": "object",
        "description": "A stunt the character can use.",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the stunt"
          },
          "description": {
            "type": "string",
            "description": "A description of the stunt describe the mechanical or narrative effect of the stunt and the conditions under which it applies."
          },
          "parameters": {
            "type": "object",
            "description": "The details of the mechanical effect of a stunt.",
            "properties": {
              "trait": {
                "type": "string",
                "description": "The trait (from the 'trait[].name' list) that the mechanics of this stunt applies."
              },
              "modifier": {
                "type": "integer",
                "description": "How many points should be applied as the mechanical effect of the stunt. It can either add to a roll or the shifts of effect from the roll when successful.",
                "minimum": 1
              },
              "actions": {
                "type": "array",
                "description": "The action types to which the mechanical effect applies.",
                "items": {
                  "enum": [
                    "Overcome",
                    "CaA",
                    "Defend",
                    "Attack"
                  ]
                },
                "uniqueItems": true,
                "minItems": 1
              },
              "modificationType": {
                "type": "string",
                "description": "The part of the resolution task to which the modifier is applied, either the total of the roll, or the total of the effect when the roll is successful.",
                "enum": [
                  "roll",
                  "effect"
                ],
                "default": "roll"
              }
            }
          }
        },
        "required": [
          "description"
        ]
      }
    },
    "tracks": {
      "type": "array",
      "description": "The data structures used to track the current state of the character.",
      "items": {
        "type": "object",
        "properties": {
          "trackId": {
            "type": "string",
            "description": "A unique identifier for this track on the character to which it is tied."
          },
          "trackLabel": {
            "type": "string",
            "description": "The label or title for this track."
          },
          "showSoakAmount": {
            "type": "boolean",
            "description": "Should the amount of soak the boxes in this track be displayed to the user?"
          },
          "boxes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "isUsed": {
                  "type": "boolean",
                  "description": "Has the box been used to soak shifts of effect?"
                },
                "soakValue": {
                  "type": "number",
                  "description": "How many shifts of effect the box can soak."
                }
              },
              "required": [
                "isUsed",
                "soakValue"
              ]
            }
          },
          "aspect": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "The Aspect representing the consequence in this track."
              },
              "freeInvokes": {
                "type": "number",
                "description": "How many Free Invokes the consequence already has."
              },
              "state": {
                "type": "string",
                "enum": [
                  "free",
                  "used",
                  "recovering"
                ]
              }
            },
            "required": [
              "name",
              "freeInvokes",
              "state"
            ]
          }
        },
        "required": [
          "trackId"
        ]
      }
    },
    "notes": {
      "title": "Notes",
      "description": "Section for notes about the character",
      "type": "array",
      "items": {
        "description": "A line of a multi-text notes field. Supports Markdown",
        "type": "string"
      }
    },
    "tags": {
      "title": "Tags",
      "description": "Arbitrary tags to be applied to the character.",
      "type": "array",
      "items": {
        "title": "Tag",
        "description": "A tag that applies to a character.",
        "type": "string",
        "minLength": 2
      }
    }
  },
  "required": [
    "type",
    "schemaVersion",
    "id",
    "name"
  ]
}

=== johnhelmuth/cluster-map/data/characters/templates/NPC.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "XXXX",
  "name": "",
  "description": "",
  "campaigns": [],
  "characterType": "NPC",
  "aspects": [
    {
      "name": ""
    }
  ],
  "traitType": "other",
  "traits": [
    {
      "name": "Good at",
      "rank": 2
    },
    {
      "name": "Bad at",
      "rank": 0
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/chris.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "chris",
  "name": "\"Chris\", of the Starfighter Chrysalis",
  "playerName": "Evan",
  "description": "A \"Thri-kreen\"-style ant-man. \n\nTwo feet worth of articulating black antennae covered with spines like tube-cleaning brushes. Brassy carapace moulted every few days. \n\nAnt-like face, black mandibles. Wide compound eyes, each lens a subtly different shade, sees in black-and-white at a wide angle. \n\nTwo true-arms from the shoulder, and two shorter footarms from the lower ribs. Two sets of joints on each limb. \n\nSimilarly oddly jointed lower limbs. (Lower locked to mimic human motions.) Vestigial wings (more nubs than anything)",
  "campaigns": ["campaign-1"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Escort Pilot From An Infamous Swarm Species"
    },
    {
      "aspectType": "Trouble",
      "name": "The Syndicate Sources the Substrates of My Pheromones"
    },
    {
      "name": "Craving Help On The Search For The Princess"
    },
    {
      "name": "No One Should Have To Face Danger Alone"
    },
    {
      "name": "Slow To Trust"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Pilot",
      "rank": 4
    },
    {
      "name": "Fight",
      "rank": 3
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Provoke",
      "rank": 2
    },
    {
      "name": "Notice",
      "rank": 2
    },
    {
      "name": "Physique",
      "rank": 2
    },
    {
      "name": "Academics",
      "rank": 1
    },
    {
      "name": "Engineering",
      "rank": 1
    },
    {
      "name": "Rapport",
      "rank": 1
    },
    {
      "name": "Will",
      "rank": 1
    },
    {
      "name": "Stealth",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "stunts": [
    {
      "name": "Specialist: Orbital Mechanics",
      "description": "???"
    },
    {
      "name": "Tough as Nails",
      "description": "Once per session, at the cost of a fate point, I can reduce the severity of a moderate consequence that's physical in nature to a mild consequence (if your mild consequence slot is free), or erase a mild consequence altogether."
    },
    {
      "name": "Inhaler of Soldier-Caste Pheromones",
      "description": "Once per scene, as a free action, can inhale a type of pheromone, and creates an Aspect like \"Fixated on [Soldier-Caste Priority]\""
    }
  ],
  "notes": [
    "Walks bipedally to put people at ease, quadrupedally on foot-arms when alone. A minimally patched, torn, gray, monochrome flight suit for the benefit of mammals identifying his role.",
    "",
    "Speaks in clicks and chirps, and sawing his antennae on each other to make noise. (Enjoys violins.)",
    "",
    "Flame-retardant somewhat-torn system-agnostic flight suit and jacket: minimally patched. Thinks it puts aliens at ease.",
    "",
    "Bandolier: Click-to-speech device + bags/slots for rip-bags, syringes, pheromone inhalers, stims + painkillers and epinephrine (for mammals).",
    "",
    "\"Am I missing the human element?\" check-phrase."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/dalton-murrieta.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "dalton-murrieta",
  "name": "Dalton Murrieta",
  "playerName": "Pete",
  "description": "",
  "campaigns": ["one-shot-3"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Shady Interstellar Trader"
    },
    {
      "aspectType": "Trouble",
      "name": "Lady Zanetti Wants her Money!"
    },
    {
      "aspectType": "Oneshot Reason",
      "name": "I owe Ikari money from last time",
      "description": "Murrieta acquired a data card from Ikari Kintsugi that she lifted from another spacer merchant, in exchange for some Seed cash and one of those fancy spacer pocket watches.\n\nThe card was the other merchant's anonymous crypto currency, that needs to be exchanged in Bane's Eye."
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Deceive",
      "rank": 4
    },
    {
      "name": "Empathy",
      "rank": 3
    },
    {
      "name": "Investigate",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "notes": [
    "Nickname: Murri"
  ]
}

=== johnhelmuth/cluster-map/data/characters/NPCs/captain-martinez.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "captain-martinez",
  "name": "Captain Marco Martinez",
  "description": "",
  "campaigns": ["campaign-2"],
  "characterType": "NPC",
  "aspects": [
    {
      "name": "Narcissistic entitled \"War Hero\" promoted to the level of his incompetence."
    },
    {
      "name": "I don't have a drinking problem.",
      "description": "I drink, I get drunk, I fall down. No problem."
    },
    {
      "name": "\"I'll get to the requisitions when I get to them, and not a minute before!\""
    },
    {
      "name": "My shit-list is pretty long, and Delilah Land is on top."
    }
  ],
  "traitType": "other",
  "traits": [
    {
      "name": "Knowing people in high places",
      "rank": 2
    },
    {
      "name": "Everything else",
      "rank": 0
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        }
      ]
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/NPCs/sample-character2.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "1",
  "name": "Carla",
  "characterType": "NPC",
  "aspects": [
    {
      "name": "Valuable assistant",
      "freeInvokes": 0
    }],
  "traitType": "approach",
  "traits": [
    {
      "name": "Careful",
      "rank": 3
    },
    {
      "name": "Clever",
      "rank": 2
    },
    {
      "name": "Forceful",
      "rank": 2
    },
    {
      "name": "Flashy",
      "rank": 1
    },
    {
      "name": "Quickly",
      "rank": 1
    },
    {
      "name": "Sneaky",
      "rank": 0
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "boxes": [
        {
          "isUsed": true,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 1
        }
      ]
    }
  ],
  "tags": ["assistant", "plucky", "sarcastic"]
}

=== johnhelmuth/cluster-map/data/characters/PCs/lou-dobb.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "lou-dobb",
  "name": "Lou Dobb",
  "playerName": "Pete",
  "characterType": "PC",
  "campaigns": ["one-shot-1"],
  "description": "He's a vat clone, so he looks like Lee Majors.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Competitive Vat Clone Pilot"
    },
    {
      "aspectType": "Trouble",
      "name": "Dohpaz Vito is Not Sure I Was a Good Investment"
    },
    {
      "aspectType": "Reason to Race",
      "name": "If I Can't Be the Best, I'll Be Unique"
    },
    {
      "name": "Vat Clones Don't Panic"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Pilot",
      "rank": 5
    },
    {
      "name": "Physique",
      "rank": 4
    },
    {
      "name": "Athletics",
      "rank": 4
    },
    {
      "name": "Will",
      "rank": 3
    },
    {
      "name": "Stealth",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/dwabit.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "dwabit",
  "name": "Dwabit",
  "playerName": "Jon",
  "description": "",
  "campaigns": ["campaign-2"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Tardigrada Teamster"
    },
    {
      "aspectType": "Trouble",
      "name": ""
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Physique",
      "rank": 4
    },
    {
      "name": "Contacts",
      "rank": 3
    },
    {
      "name": "Fight",
      "rank": 3
    },
    {
      "name": "Pilot",
      "rank": 2
    },
    {
      "name": "Resources",
      "rank": 2
    },
    {
      "name": "Stealth",
      "rank": 2
    },
    {
      "name": "Burglary",
      "rank": 1
    },
    {
      "name": "Deceive",
      "rank": 1
    },
    {
      "name": "Notice",
      "rank": 1
    },
    {
      "name": "Rapport",
      "rank": 1
    }
  ],
  "stunts": [
    {
      "name": "Percussive Maintenance",
      "description": "Substitute Physique for Engineering for Overcome rolls when trying to fix technology by smacking it."
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/delano-mack.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "delano-mack",
  "name": "Delano Mack",
  "playerName": "Pete",
  "characterType": "PC",
  "campaigns": ["campaign-1"],
  "description": "Short, 2nd rate Han Solo looking human.",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Independent Carrier, Captain of the Jitterbug"
    },
    {
      "aspectType": "Trouble",
      "name": "They think they are better than me"
    },
    {
      "name": "I was an Explorer Scout and have Outdoors experience"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Investigate",
      "rank": 4
    },
    {
      "name": "Shoot",
      "rank": 3
    },
    {
      "name": "Pilot",
      "rank": 3
    },
    {
      "name": "Provoke",
      "rank": 2
    },
    {
      "name": "Athletics",
      "rank": 2
    },
    {
      "name": "Fight",
      "rank": 2
    },
    {
      "name": "Rapport",
      "rank": 1
    },
    {
      "name": "Engineering",
      "rank": 1
    },
    {
      "name": "Notice",
      "rank": 1
    },
    {
      "name": "Deceive",
      "rank": 1
    },
    {
      "name": "Empathy",
      "rank": 1
    }
  ],
  "stunts": [
    {
      "name": "Tuck and Roll Under Fire",
      "description": "+2 on Athletics checks when Defending from ranged weapon fire when there is cover near by me",
      "parameters": {
        "trait": "Athletics",
        "modifier": 2,
        "actions": ["Defend"],
        "modificationType": "roll"
      }
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        },
        {
          "isUsed": false,
          "soakValue": 3
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}
