=== johnhelmuth/cluster-map/data/schemas/clusters.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://in-dire-straits.space/data/schemas/clusters.schema.json",
  "title": "Clusters",
  "description": "A dataset of all of the clusters of star systems in a Role Playing Game.",
  "type": "object",
  "properties": {
    "type": {
      "description": "The type of thingy the data describes, 'clusters'.",
      "type": "string"
    },
    "schemaVersion": {
      "description": "The version of the schema for the data.",
      "type": "string",
      "const": "2"
    },
    "currentClusterId": {
      "description": "The ID of the cluster that is currently being viewed.",
      "type": "string"
    },
    "clusters": {
      "description": "The list of clusters in the dataset.",
      "type": "array",
      "items": {
        "description": "A cluster in the dataset.",
        "$ref": "https://in-dire-straits.space/data/schemas/cluster.schema.json"
      }
    }
  },
  "required": [ "clusters" ]
}

=== johnhelmuth/cluster-map/data/clusters/clusters-in-dire-straits-campaign.json
{
  "schemaVersion": "2",
  "type": "clusters",
  "currentClusterId": "DLC",
  "clusters": [
    {
      "schemaVersion": "2",
      "type": "cluster",
      "id": "DLC",
      "name": "In Dire Straits Cluster",
      "systems": [
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "0",
          "name": "Avarax",
          "attributes": {
            "technology": -2,
            "environment": -1,
            "resources": -1
          },
          "aspects": [
            "Recovering from a Devastating Invasion",
            "\"We're Blockaded for Our Own Good\""
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/avarax",
          "position": {
            "x": 130,
            "y": 130
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "1",
          "name": "Willful",
          "attributes": {
            "technology": 0,
            "environment": 0,
            "resources": -1
          },
          "aspects": [
            "Clawed our Way off the Planet, What's next?",
            "Need More Unobtainium"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/willful",
          "position": {
            "x": 650,
            "y": 90
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "2",
          "name": "Bane's Eye",
          "attributes": {
            "technology": 3,
            "environment": 0,
            "resources": -2
          },
          "aspects": [
            "Ambitious, but methodical for their own survival",
            "Our god is always watching what we do"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/banes-eye",
          "position": {
            "x": 895,
            "y": 200
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "3",
          "name": "Dragongull's Cry",
          "attributes": {
            "technology": 0,
            "environment": 0,
            "resources": 1
          },
          "aspects": [
            "Everything Can Be Found In The Ocean",
            "\"Never Trust a Human\""
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/dragongulls-cry",
          "position": {
            "x": 875,
            "y": 475
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "4",
          "name": "Dalderana",
          "attributes": {
            "technology": 0,
            "environment": 1,
            "resources": -1
          },
          "aspects": [
            "Owe those bastards for our Space Program",
            "Obsessed with the TattTubers"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/dalderana",
          "position": {
            "x": 630,
            "y": 300
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "5",
          "name": "Concordist",
          "attributes": {
            "technology": 0,
            "environment": 0,
            "resources": 1
          },
          "aspects": [
            "Secretive",
            "Hedonistic"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/concordist",
          "position": {
            "x": 300,
            "y": 260
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "6",
          "name": "Golden Seed",
          "attributes": {
            "technology": -2,
            "environment": 1,
            "resources": 4
          },
          "aspects": [
            "The Pulsar Only Cooks One Hemisphere.",
            "\"They Think That Nothing Bad Can Happen To Them!\""
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/golden-seed",
          "position": {
            "x": 620,
            "y": 575
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "7",
          "name": "Ceti Daenia",
          "attributes": {
            "technology": 0,
            "environment": -2,
            "resources": -1
          },
          "aspects": [
            "Balkanized Dome City States On Planet, Tentative Off Planet Coalition"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/ceti-daenia",
          "position": {
            "x": 100,
            "y": 400
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "8",
          "name": "Zerzi",
          "attributes": {
            "technology": 1,
            "environment": -2,
            "resources": 2
          },
          "aspects": [
            "Aggressively Industrialized",
            "The only thing that matters is right now,\nthe future will take care of itself"
          ],
          "url": "/tatterpedia/places/clusters/local-cluster/zerzi",
          "position": {
            "x": 375,
            "y": 665
          }
        },
        {
          "schemaVersion": "2",
          "type": "system",
          "id": "9",
          "name": "Luxia",
          "attributes": {
            "technology": 1,
            "environment": -1,
            "resources": -2
          },
          "aspects": [
            "It's a prison planet, were you expecting cake?",
            "You can get blood if you find the right stone"
          ],
          "position": {
            "x": 130,
            "y": 620
          }
        }
      ],
      "straits": [
        {
          "type": "strait",
          "schemaVersion": "2",
          "systems": [
            "0",
            "1"
          ],
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "0"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "1"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "1"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "2"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "1"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "3"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "1"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "4"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "2"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "3"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "3"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "4"
          }
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "3"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "5"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "3"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "6"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "4"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "5"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "5"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "6"
          },
          "direction": "counterclockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "5"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "7"
          },
          "direction": "counterclockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "6"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "7"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
            "systemId": "6"
          },
          "straitPointB": {
            "clusterId": "DLC",
            "systemId": "8"
          },
          "direction": "clockwise"
        },
        {
          "type": "strait",
          "schemaVersion": "2",
          "straitPointA": {
            "clusterId": "DLC",
